mapbox/vision-ios-examples

Resources/en.lproj/Localizable.strings, demo/ContainerInteractor.swift, demo/ContainerViewController.swift, demo/MenuViewController.swift, demo/PaddedLabel.swift
Depends on: https://github.com/mapbox/mapbox-vision-ios/pull/16
=> Calibration

demo/ContainerInteractor.swift
Depends on: https://github.com/mapbox/mapbox-vision-ios/pull/17
=> Update model switching

demo/ContainerInteractor.swift, demo/Signs.swift
Use Country determined by `MapboxVision`.
Part of https://github.com/mapbox/cv-assist/issues/670
Depends on https://github.com/mapbox/mapbox-vision-ios/pull/42
=> Market country

demo/ContainerInteractor.swift
Depends on: https://github.com/mapbox/mapbox-vision-ios/pull/56
=> Update to external video source

demo.xcodeproj/project.pbxproj, scripts/carthage-input.xcfilelist
Deps:
https://github.com/mapbox/cv-assist/pull/847
https://github.com/mapbox/mapbox-vision-ios/pull/75
=> Rename Core modules to Native modules

demo.xcodeproj/project.pbxproj, demo/AppDelegate.swift, demo/CollisionObjectView.swift, demo/ContainerViewController.swift, demo/DistanceFormatter.swift, demo/License/WelcomeViewController.swift, demo/PaddedLabel.swift
Migration to Swift4.2
related to https://github.com/mapbox/mapbox-vision-ios/issues/83
=> Swift 4.2 support

demo/Signs.swift
=> Sign assets for unknown country

README.md
Includes updated version of required dependency (Carthage) to avoid issue with `Xcode 10.2+`.
Please see https://github.com/Carthage/Carthage/issues/2691 for more details
=> Minor update in README file

demo.xcodeproj/xcshareddata/xcschemes/demo.xcscheme
Checks:
Linked PRs: mapbox/mapbox-vision#1134, mapbox/mapbox-vision#1133
=> Update Xcode project settings

scripts/carthage-input.xcfilelist
=> Add MapboxAccounts.framework to carthage copy phase

CHANGELOG.md, Cartfile
=> Release 0.7.0 to dev

demo/RoadLanesView.swift, demo/Signs.swift
Checks:
Linked issues:
Blocked by https://github.com/mapbox/mapbox-vision/issues/1593
=> Add missing signs

CHANGELOG.md, demo/ARContainerViewController.swift, demo/ContainerInteractor.swift, demo/ContainerViewController.swift
=> New ar integration

demo/SafetyState.swift
=> Add construction cone class

demo/ARContainerViewController.swift, demo/ContainerInteractor.swift, demo/ContainerViewController.swift
Checks:
Linked issues:
https://github.com/mapbox/mapbox-vision/issues/1698
=> Update SDK usages

CHANGELOG.md, Resources/Info.plist
Checks:
Linked issues:
Resolves #122
=> Remove location update in background

demo/ARContainerViewController.swift, demo/ARRoute+DirectionsRoute.swift
Checks:
Linked issues:
ios part of mapbox/mapbox-vision#2024
=> AR features toggle

Matchfile
Checks:
Linked issues:
Resolves #2134
=> Support match for Teaser

demo/ContainerInteractor.swift
Checks:
Linked issues:
iOS part of mapbox/mapbox-vision#2020
Merge only after mapbox/mapbox-vision-ios#274
=> Adapt to model performance API change

CHANGELOG.md, Cartfile
Checks:
Linked issues:
mapbox/mapbox-vision#2314
=> Merge Release/0.12.0 branch into dev

demo.xcodeproj/project.pbxproj
Checks:
Linked issues:
resolves #147
=> Update Xcode project format to Xcode 11.0-compatible.

CHANGELOG.md, Cartfile
=> Release 0.13.1
